services:
  - type: web
    name: your-validator
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    rootDir: python/id_photo_validator
